version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: discord_frontend
    ports:
      -'8080:8080'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules
    stdin_open: true
    tty: true

  server:
    build: ./server
    container_name: discord_server
    ports:
      -"5000:5000"
    volumes:
      - ./server:/app
      - ./server/node_modules
      